utils::globalVariables(
  c(
    ".",
    "alignment_not_unique",
    "ambiguous",
    "end",
    "gene_name",
    "locus_tag",
    "log2FoldChange",
    "no_feature",
    "not_aligned",
    "padj",
    "product_description",
    "product_name",
    "q_val",
    "start",
    "strand",
    "too_low_a_qual",
    "total_count"
  )
)
