#' Create plotly figures from MultiQC
#'
#' @param directory Folder containing all the data files generated by MultiQC,
#'   e.g. "multiqc/multiqc_data/".
#'
#' @return List of `plotly` plot objects and the data being plotted.
#' @export
#'
#' @import dplyr
#' @import purrr
#' @import tibble
#' @import janitor
#'
#' @description Creates three plotly figures from MultiQC results, and returns
#'   the data along with the plot objects.
#'
#' @references None.
#'
#' @seealso <https://www.github.com/travis-m-blimkie/tRavis>
#'
#' @examples
#' \dontrun{
#'   tr_qc_plots("multiqc_data/")
#' }
#'
tr_qc_plots <- function(directory) {

  # FastQC ----------------------------------------------------------------

  json_all <- rjson::fromJSON(
    file = list.files(
      directory, pattern = "multiqc_data.json", full.names = TRUE
    ),
    simplify = TRUE
  )

  fastqc_list <- json_all %>%
    pluck("report_plot_data") %>%
    pluck("fastqc_per_base_sequence_quality_plot") %>%
    pluck("datasets") %>%
    flatten()

  fastqc_names <- fastqc_list %>% map(~pluck(., "name"))

  fastqc_data <- fastqc_list %>% map(
    ~pluck(., "data") %>%
      map(~tibble(Base_Position = .[[1]], Phred_Score = .[[2]])) %>%
      bind_rows()
  )

  fastqc_final <- map2(
    fastqc_names,
    fastqc_data,
    ~add_column(.y, sample = rep(.x), .before = 1)
  ) %>%
    bind_rows()

  read_length <- max(fastqc_final$Base_Position)

  fastqc_plot <- plotly::plot_ly(
    group_by(fastqc_final, sample),
    x = ~Base_Position,
    y = ~Phred_Score,
    type = "scatter",
    mode = "lines",
    line = list(color = "grey"),
    hoverinfo = "text",
    hovertext = ~paste0(
      "Sample: ", sample
    )
  ) %>%
    plotly::layout(
      xaxis = list(
        title = "Base Position",
        showline = TRUE,
        mirror = "ticks"
      ),
      yaxis = list(
        title = "Phred Score",
        range = c(0, max(fastqc_final$Phred_Score) + 2),
        showline = TRUE,
        mirror = "ticks"
      ),
      title = "<b>FastQC: Phred Scores</b>",
      shapes = list(
        list(
          type = "rect",
          fillcolor = "red",
          line = list(color = "red"),
          opacity = 0.1,
          x0 = 0,
          x1 = (read_length + 2),
          xref = "x",
          y0 = 0,
          y1 = 20,
          yref = "y"
        ),
        list(
          type = "rect",
          fillcolor = "orange",
          line = list(color = "orange"),
          opacity = 0.1,
          x0 = 0,
          x1 = (read_length + 2),
          xref = "x",
          y0 = 20,
          y1 = 28,
          yref = "y"
        ),
        list(
          type = "rect",
          fillcolor = "green",
          line = list(color = "green"),
          opacity = 0.1,
          x0 = 0,
          x1 = (read_length + 2),
          xref = "x",
          y0 = 28,
          y1 = 50,
          yref = "y"
        )
      )
    ) %>%
    plotly::style(
      hoverlabel = list(bgcolor = "white", bordercolor = "black")
    )


  # STAR ------------------------------------------------------------------

  star_raw <- read_tsv(
    list.files(directory, pattern = "multiqc_star.txt", full.names = TRUE),
    col_types = cols()
  ) %>% clean_names()

  star_tidy <- star_raw %>%
    arrange(sample) %>%
    mutate(sample = factor(sample, rev(sample)))

  star_plot <- plotly::plot_ly(
    star_tidy,
    x = ~uniquely_mapped,
    y = ~sample,
    type = "bar",
    hoverinfo = "text",
    hovertext = ~paste0(
      "<b>Uniquely Mapped: </b>", uniquely_mapped, " (", uniquely_mapped_percent, "%)<br>",
      "<b>Multimapped: </b>", multimapped, " (", multimapped_percent, "%)<br>",
      "<b>Multimapped Too Many: </b>", multimapped_toomany, " (", multimapped_toomany_percent, "%)<br>",
      "<b>Unmapped Too Short: </b>", unmapped_tooshort, " (", unmapped_tooshort_percent, "%)<br>",
      "<b>Unmapped Other: </b>", unmapped_other, " (", unmapped_other_percent, "%)"
    ),
    marker = list(color = "#437bb1"),
    name = "Uniquely Mapped"
  ) %>%
    plotly::add_trace(
      x = ~multimapped,
      y = ~sample,
      type = "bar",
      marker = list(color = "#7cb5ec"),
      name = "Mapped to multiple loci"
    ) %>%
    plotly::add_trace(
      x = ~multimapped_toomany,
      y = ~sample,
      type = "bar",
      marker = list(color = "#eda467"),
      name = "Mapped to too many loci"
    ) %>%
    plotly::add_trace(
      x = ~unmapped_tooshort,
      y = ~sample,
      type = "bar",
      marker = list(color = "#b1084c"),
      name = "Unmapped: too short"
    ) %>%
    plotly::add_trace(
      x = ~unmapped_other,
      y = ~sample,
      type = "bar",
      marker = list(color = "#7f0000"),
      name = "Unmapped: other"
    ) %>%
    plotly::layout(
      barmode = "stack",
      xaxis = list(title = "Number of Reads"),
      yaxis = list(title = ""),
      legend = list(orientation = "h", y = -0.15),
      title = "<b>STAR: Aligned Reads</b>"
    ) %>%
    plotly::style(
      hoverlabel = list(bgcolor = "white", bordercolor = "black")
    )


  # HTSeq -----------------------------------------------------------------

  htseq_raw <- read_tsv(
    list.files(directory, pattern = "multiqc_htseq.txt", full.names = TRUE),
    col_types = cols()
  ) %>%
    clean_names() %>%
    mutate(sample = str_remove(sample, "\\.count"))

  htseq_tidy <- htseq_raw %>%
    arrange(sample) %>%
    mutate(
      ambiguous_percent = ambiguous / total_count,
      alignment_not_unique_percent = alignment_not_unique / total_count,
      no_feature_percent = no_feature / total_count,
      too_low_a_qual_percent = too_low_a_qual / total_count,
      not_aligned_percent = not_aligned / total_count,
      sample = factor(sample, rev(sample))
    ) %>%
    mutate(across(contains("percent"), signif, digits = 3))

  htseq_plot <- plotly::plot_ly(
    htseq_tidy,
    x = ~assigned,
    y = ~sample,
    type = "bar",
    hoverinfo = "text",
    hovertext = ~paste0(
      "<b>Assigned: </b>", assigned, " (", percent_assigned, "%)<br>",
      "<b>Ambiguous: </b>", ambiguous, " (", ambiguous_percent, "%)<br>",
      "<b>Alignment not unique: </b>", alignment_not_unique, " (", alignment_not_unique_percent, "%)<br>",
      "<b>No feature: </b>", no_feature, " (", no_feature_percent, "%)<br>",
      "<b>Too low aQual: </b>", too_low_a_qual, " (", too_low_a_qual_percent, "%)<br>",
      "<b>Not aligned: </b>", not_aligned, " (", not_aligned_percent, "%)"
    ),
    marker = list(color = "#7cb5ec"),
    name = "Assigned"
  ) %>%
    plotly::add_trace(
      x = ~ambiguous,
      y = ~sample,
      type = "bar",
      marker = list(color = "#434348"),
      name = "Ambiguous"
    ) %>%
    plotly::add_trace(
      x = ~alignment_not_unique,
      y = ~sample,
      type = "bar",
      marker = list(color = "#90ed7d"),
      name = "Alignment not unique"
    ) %>%
    plotly::add_trace(
      x = ~no_feature,
      y = ~sample,
      type = "bar",
      marker = list(color = "#f7a35c"),
      name = "No feature"
    ) %>%
    plotly::add_trace(
      x = ~too_low_a_qual,
      y = ~sample,
      type = "bar",
      marker = list(color = "#8085e9"),
      name = "Too low aQual"
    ) %>%
    plotly::add_trace(
      x = ~not_aligned,
      y = ~sample,
      type = "bar",
      marker = list(color = "#f15c80"),
      name = "Not aligned"
    ) %>%
    plotly::layout(
      barmode = "stack",
      xaxis = list(title = "Number of Counts"),
      yaxis = list(title = ""),
      legend = list(orientation = "h", y = -0.15),
      title = "<b>HTSeq-count: Gene Counts</b>"
    ) %>%
    plotly::style(
      hoverlabel = list(bgcolor = "white", bordercolor = "black")
    )


  # Return all output as a list -------------------------------------------

  return(list(
    "fastqc" = fastqc_plot,
    "star"   = star_plot,
    "htseq"  = htseq_plot,
    "data" = list(
      "fastqc" = fastqc_final,
      "star"   = star_tidy,
      "htseq"  = htseq_tidy
    )
  ))
}
